group=dev.brahmkshatriya.runtimeloader
version=0.1.0
projectName=Kotlin Runtime Loader
projectDescription=Attach separately compiled Kotlin code to a running Kotlin Multiplatform application while preserving the host runtime and object graph.
projectUrl=https://github.com/brahmkshatriya/runtimeloader
developerId=brahmkshatriya
developerName=Shivam
developerUrl=https://github.com/brahmkshatriya
licenseName=Apache License, Version 2.0
licenseUrl=https://www.apache.org/licenses/LICENSE-2.0.txt
