package dev.brahmkshatriya.runtimeloader

import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine

/** A separately compiled code artifact attached to the current Kotlin runtime. */
public interface LoadedCode {
    public val path: String
    public val isClosed: Boolean

    /**
     * Releases resources owned by this handle when the platform supports it.
     *
     * Some runtimes (Android, Wasm, Kotlin/Native) cannot forcibly unload attached code. On those
     * platforms close() only releases/marks this handle; callers must not assume code was unmapped.
     */
    public fun close()
}

public class RuntimeLoaderException(message: String, cause: Throwable? = null) :
    IllegalStateException(message, cause)

/**
 * Application-owned authenticity/integrity verification performed before executable code is loaded.
 *
 * Runtime Loader's native ABI fingerprints are compatibility metadata, not a trust mechanism. A
 * verifier should authenticate the artifact (and any sidecars it relies on) against a trusted root
 * such as a signed catalog or a pinned digest. Throw on failure.
 */
public fun interface RuntimeCodeVerifier {
    public fun verify(path: String)
}

/** Stable generated entry names shared by the Gradle module plugin and runtime helpers. */
public object RuntimeLoaderEntryPoint {
    public const val CLASS_NAME: String =
        "dev.brahmkshatriya.runtimeloader.generated.RuntimeLoaderGeneratedEntry"
    public const val WASM_EXPORT_NAME: String = "runtimeExtensionCreate"
    public const val NATIVE_SYMBOL_NAME: String =
        "kfun:dev.brahmkshatriya.runtimeloader.generated#runtimeExtensionCreate(){}" +
            "kotlinx.cinterop.CPointer<out|kotlinx.cinterop.CPointed>"
}

/** Platform implementation used by [createEntry]. */
public expect fun LoadedCode.createEntryUntyped(): Any

/**
 * Instantiate the consumer-owned contract entry generated by the Runtime Loader module plugin.
 *
 * Runtime Loader never knows the extension API type itself; the caller supplies that type and the
 * generated module entry is checked against it in the host runtime.
 */
public inline fun <reified T : Any> LoadedCode.createEntry(): T {
    val value = createEntryUntyped()
    if (value !is T) {
        throw RuntimeLoaderException(
            "Runtime-loaded entry does not implement the requested host contract"
        )
    }
    return value
}

/**
 * Platform-independent low-level entry point for attaching code to the current runtime.
 *
 * This function does not authenticate [path]. Callers loading downloaded/untrusted artifacts should
 * use [loadVerified] (or perform an equivalent application-owned verification) first.
 */
public expect object RuntimeCodeLoader {
    public fun load(
        path: String,
        onLoaded: (LoadedCode) -> Unit,
        onError: (Throwable) -> Unit = { throw it },
    )
}

/** Verify application trust policy before delegating to [load]. */
public fun RuntimeCodeLoader.loadVerified(
    path: String,
    verifier: RuntimeCodeVerifier,
    onLoaded: (LoadedCode) -> Unit,
    onError: (Throwable) -> Unit = { throw it },
) {
    try {
        verifier.verify(path)
    } catch (failure: Throwable) {
        onError(failure)
        return
    }
    load(path, onLoaded, onError)
}

/** Coroutine convenience wrapper around [RuntimeCodeLoader.load]. */
public suspend fun loadCode(path: String): LoadedCode = suspendCoroutine { continuation ->
    RuntimeCodeLoader.load(
        path = path,
        onLoaded = continuation::resume,
        onError = continuation::resumeWithException,
    )
}


/** Coroutine convenience wrapper that applies [verifier] before executable loading. */
public suspend fun loadVerifiedCode(path: String, verifier: RuntimeCodeVerifier): LoadedCode =
    suspendCoroutine { continuation ->
        RuntimeCodeLoader.loadVerified(
            path = path,
            verifier = verifier,
            onLoaded = continuation::resume,
            onError = continuation::resumeWithException,
        )
    }
