package dev.brahmkshatriya.runtimeloader.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

internal const val RUNTIME_LOADER_GENERATED_ENTRY_CLASS =
    "dev.brahmkshatriya.runtimeloader.generated.RuntimeLoaderGeneratedEntry"
internal const val RUNTIME_LOADER_WASM_ENTRY = "runtimeExtensionCreate"
internal const val RUNTIME_LOADER_NATIVE_ENTRY =
    "kfun:dev.brahmkshatriya.runtimeloader.generated#runtimeExtensionCreate(){}" +
        "kotlinx.cinterop.CPointer<out|kotlinx.cinterop.CPointed>"

@CacheableTask
abstract class GenerateRuntimeLoaderEntryTask : DefaultTask() {
    @get:Input
    @get:Optional
    abstract val contract: Property<String>

    @get:Input
    @get:Optional
    abstract val implementation: Property<String>

    @get:OutputDirectory
    abstract val commonOutputDirectory: DirectoryProperty

    @get:OutputDirectory
    abstract val wasmOutputDirectory: DirectoryProperty

    @get:OutputDirectory
    abstract val nativeOutputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val roots = listOf(
            commonOutputDirectory.get().asFile,
            wasmOutputDirectory.get().asFile,
            nativeOutputDirectory.get().asFile,
        )
        roots.forEach { root ->
            root.deleteRecursively()
            root.mkdirs()
        }

        val configuredContract = contract.orNull?.trim().orEmpty()
        val configuredImplementation = implementation.orNull?.trim().orEmpty()
        if (configuredContract.isEmpty() && configuredImplementation.isEmpty()) return
        if (configuredContract.isEmpty() || configuredImplementation.isEmpty()) {
            throw GradleException(
                "runtimeLoaderModule.entry requires both contract and implementation when entry generation is enabled"
            )
        }

        write(
            commonOutputDirectory.get().asFile,
            "dev/brahmkshatriya/runtimeloader/generated/RuntimeLoaderGeneratedEntry.kt",
            """
                package dev.brahmkshatriya.runtimeloader.generated

                // Generated by dev.brahmkshatriya.runtime-loader.module.
                // Interface delegation makes the configured implementation compile-time checked
                // against the consumer-owned contract without Runtime Loader knowing that contract.
                public class RuntimeLoaderGeneratedEntry : $configuredContract by $configuredImplementation()
            """.trimIndent() + "\n",
        )
        write(
            wasmOutputDirectory.get().asFile,
            "dev/brahmkshatriya/runtimeloader/generated/RuntimeLoaderWasmEntry.kt",
            """
                @file:OptIn(kotlin.js.ExperimentalJsExport::class, kotlin.js.ExperimentalWasmJsInterop::class)

                package dev.brahmkshatriya.runtimeloader.generated

                import kotlin.js.JsExport
                import kotlin.js.JsReference
                import kotlin.js.toJsReference

                @JsExport
                public fun runtimeExtensionCreate(): JsReference<Any> =
                    RuntimeLoaderGeneratedEntry().toJsReference()
            """.trimIndent() + "\n",
        )
        write(
            nativeOutputDirectory.get().asFile,
            "dev/brahmkshatriya/runtimeloader/generated/RuntimeLoaderNativeEntry.kt",
            """
                @file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

                package dev.brahmkshatriya.runtimeloader.generated

                import kotlinx.cinterop.COpaquePointer
                import kotlinx.cinterop.StableRef

                public fun runtimeExtensionCreate(): COpaquePointer =
                    StableRef.create(RuntimeLoaderGeneratedEntry()).asCPointer()
            """.trimIndent() + "\n",
        )
    }

    private fun write(root: File, relativePath: String, text: String) {
        val output = root.resolve(relativePath)
        output.parentFile.mkdirs()
        output.writeText(text)
    }
}
